skip_strings:
  /:
    - cipher
    - cypher
    - encrypt

skip_paths:
  - .*.pdf
  - .*.object
  - .*.zip
  - .*.jpg
  - .*.dat
  - .*.gif
  - .*.dll
  - .*.pf
  - .*.jar
  - .*.JPG
  - .*.PNG
  - .*.png
  - .*.xls
  - .*.SVG
  - .*.svg
  - .*.iso
  - .*.ISO

no_entropy: true
no_history: true